steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build','-f' , 'Dockerfile', '-t', 'asia-south1-docker.pkg.dev/$PROJECT_ID/podinfo-repo/podinfo:$BRANCH_NAME-$SHORT_SHA', '.']
images: ['asia-south1-docker.pkg.dev/$PROJECT_ID/podinfo-repo/podinfo:$BRANCH_NAME-$SHORT_SHA']

